feature/BI-12781-Periodically-call-cleanup-endpoint
companieshouse/configurable-api-caller pull request #26
Opened 2023-04-03 10:06 UTC by wdhda-ch

- Add profiles for delete_complete_validated_accounts
- Added resources to main.tf

Set to only deploy on development. As service is only deployed on development.
Future work required to double check staging and live profiles are still correct, when count is changed.

2023-04-03 16:35 UTC, HarryBosworth requested changes
Looks good. One potential improvement would be to change the name of the JSON files. Since this repository has entries for multiple services it would be good to easily tell which service the call is for. Other files have the service as a prefix e.g. `efs_queue_files.json` where `efs` is the service name. Maybe ours would be better named `account_validator_cleanup_submissions` instead of `delete_complete_validated_accounts`.

2023-04-11 11:39 UTC, HarryBosworth approved these changes

2023-04-21 06:47 UTC, wdhda-ch commented
Double check:
- ENDPOINT
- API_HOST
- API_KEY_REF
before merging.

2024-06-17 06:57 UTC, okoye-companieshouse approved these changes

2024-06-19 12:11 UTC, merged